### ISSUE TITLE
Native Linux setup

### ISSUE THREAD

**Issue by B00daW** [lundstroem/snibbetracker#1]
Here is the updated code to make sure that the modifier key works in Linux and the Makefile for /res/linux/.
[Makefile.txt](https://github.com/lundstroem/snibbetracker/files/3464466/Makefile.txt)

[main.c.txt](https://github.com/lundstroem/snibbetracker/files/3464467/main.c.txt)

PoroCYon helped me out a lot with this.

**Comment by jpcima** [comment]
It's nice but how about making a pull request of it?
(I'd be also interested in a Linux build)

**Comment by B00daW** [comment]
I have no experience with such matters or discourse.

**Comment by jpcima** [comment]
In this case, hi @PoroCYon, would you mind commiting the changes into a fork that we could use?

(it's not that I couldn't do so myself, but I wouldn't want to steal your contribution by doing it)

**Comment by utz82** [comment]
Thx B00daW and PoroCYon :)

A note, -static-libgcc can be dropped from linker flags on Linux.

**Comment by jpcima** [comment]
At the below repository, I pushed a few linux updates. Operation will be similar to windows.
Files will be present in system-wide locations; it will copy at the startup.
Also, the config file will be handled.

In the previous code, the `platform_linux` definition has been misplaced, and it was edited.
(although honestly, this will be better as the "unix" platform for bsd and such which don't need special consideration, and it's possibly the case for haiku as well)

`getDirectoryList` was also left unimplemented and it's been fixed.

https://github.com/linuxmao-org/snibbetracker

**Comment by trebmuh** [comment]
Hi all, just letting you know that I've been building @jpcima 's fork on a Debian Stretch machine and it builds fine. I've only launched the resulting binary to check but haven't gotten further yet.

@lundstroem what about merging that in master?

**Comment by lundstroem** [comment]
I'd be happy to if everything runs ok as well, won't be able to test myself
but other can verify :)
I'll try to find time to take a closer look at it.

/ Harry

**Comment by B00daW** [comment]
Well, everything works.  The local file path is a bit annoying in Linux and
may need a *.conf file or something if distribs want to put it in
repositories that have different path schemes. :)

**Comment by trebmuh** [comment]
@B00daW can you please check if that works for you now, and then close this issue?

**Comment by B00daW** [comment]
@trebmuh Seems to work great now. :)

**Comment by alexmyczko** [comment]
haha after i fixed it myself i find this closed issue!

for those who prefer a debian package:
http://sid.ethz.ch/debian/snibbetracker

**Comment by B00daW** [comment]
> haha after i fixed it myself i find this closed issue!
> 
> for those who prefer a debian package: http://sid.ethz.ch/debian/snibbetracker

as i revisit this, i think i noticed that maybe when you built the deb file that the modifier key was still not fixed for linux.  it also do not contain the app icon or desktop file for the ~/.local/share/applications directory

i believe it has also snuck into the ubuntu repositories as well
